[sdl]
fullscreen=false
autolock=false
windowresolution=1280x960

[dosbox]
memsize=32

[cpu]
core=auto
cputype=auto
cycles=auto

[mixer]
rate=44100
blocksize=1024

[midi]
mpu401=intelligent
mididevice=default

[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default

[autoexec]
mount c LB2
c:
scidhuv
